asp.net-assignment-4/Models/Borrowing.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace asp.net_assignment_4.Models
{
    public class Borrowing
    {
        [Key]
        [Required(ErrorMessage = "{0} is required")]
        public int Id { get; set; }
        [ForeignKey("Book")]
        [Required(ErrorMessage = "{0} is required")]
        public int BookId { get; set; }
        [ForeignKey("Reader")]
        [Required(ErrorMessage = "{0} is required")]
        public int BorrowerId { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public bool IsReturned { get; set; }

        [ValidateNever]
        public Book Book { get; set; }
        [ValidateNever]
        public Reader Reader { get; set; }
    }
}

asp.net-assignment-4/Controllers/BorrowingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using asp.net_assignment_4.Models;
using asp.net_assignment_4.Data;

namespace asp.net_assignment_4.Controllers
{
    public class BorrowingController : Controller
    {
        private readonly AppDbContext appDbContext;

        public BorrowingController(AppDbContext appDbContext)
        {
            this.appDbContext = appDbContext;
        }

        // Get all borrowings
        [HttpGet]
        [Route("borrowings")]
        public async Task<IActionResult> Index(string search)
        {
            var borrowings = appDbContext.Borrowing
                .Include(b => b.Book)
                .Include(b => b.Reader)
                .AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                borrowings = borrowings.Where(b =>  
                    b.Book.Name.Contains(search) ||
                    b.Reader.Name.Contains(search));
            }

            return View(await borrowings.ToListAsync());
        }

        // Get certain borrowing
        [HttpGet]
        [Route("borrowings/{id}")]
        public async Task<IActionResult> Details(int id)
        {
               return View(await appDbContext.Borrowing
                .Include(b => b.Book)
                .Include(b => b.Reader)
                .FirstOrDefaultAsync(b => b.Id == id));
        }

        // Get borrowing add page 
        [HttpGet]
        [Route("borrowings/add")]
        public IActionResult Add()
        {
            return View();
        }

        //Add a borrowing
        [HttpPost]
        [Route("borrowings/add")]
        public async Task<IActionResult> Add(Borrowing borrowing)
        {
            if (ModelState.IsValid)
            {
                var book = await appDbContext.Book.FindAsync(borrowing.BookId);
                var reader = await appDbContext.Reader.FindAsync(borrowing.BorrowerId);
                var newBorrowing = new Borrowing()
                {
                    BookId = borrowing.BookId,
                    BorrowerId = borrowing.BorrowerId,
                    IsReturned = borrowing.IsReturned,
                    Book = book,
                    Reader = reader,
                };
                await appDbContext.Borrowing.AddAsync(newBorrowing);
                await appDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(borrowing);
        }

        // Get borrowing edit page
        [HttpGet]
        [Route("borrowings/edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await appDbContext.Borrowing.FirstOrDefaultAsync(b => b.Id == id));
        }

        // Edit borrowing
        [HttpPost]
        [Route("borrowings/edit/{id}")]
        public async Task<IActionResult> Edit(Borrowing newBorrowing)
        {
            if (ModelState.IsValid)
            {
                var borrowing = await appDbContext.Borrowing.FindAsync(newBorrowing.Id);
                var newBook = await appDbContext.Book.FindAsync(newBorrowing.BookId);
                var newReader = await appDbContext.Reader.FindAsync(newBorrowing.BorrowerId);
                if (borrowing != null)
                {
                    borrowing.BookId = newBorrowing.BookId;
                    borrowing.BorrowerId = newBorrowing.BorrowerId;
                    borrowing.IsReturned = newBorrowing.IsReturned;
                    borrowing.Book = newBook;
                    borrowing.Reader = newReader;
                    await appDbContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(newBorrowing);
        }


        // Delete borrowing
        [Route("borrowings/delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var borrowing = await appDbContext.Borrowing.FindAsync(id);
            if (borrowing != null)
            {
                appDbContext.Borrowing.Remove(borrowing);
                await appDbContext.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

asp.net-assignment-4/Views/Borrowing/Add.cshtml
@model Borrowing
@{
    ViewData["title"] = "Add a Borrowing";
}

<h1>New Borrowing:</h1>
<form method="post" asp-controller="Borrowing" asp-action="Add">
    <label asp-for="BookId"></label>
    <input type="number" asp-for="BookId" placeholder="Enter Book Id" />
    <div>
        <span asp-validation-for="BookId"></span>
    </div>
    <label asp-for="BorrowerId"></label>
    <input type="number" asp-for="BorrowerId" placeholder="Enter Borrower Id" />
    <div>
        <span asp-validation-for="BorrowerId"></span>
    </div>
    <label asp-for="IsReturned"></label>
    <input type="checkbox" asp-for="IsReturned" />
    <div>
        <span asp-validation-for="IsReturned"></span>
    </div>
    <button type="submit">Add</button>
</form>

asp.net-assignment-4/Views/Borrowing/Details.cshtml
@model Borrowing
@{
    ViewData["title"] = "Borrowing";
}
<style>
    h2{
        font-weight:normal;
    }
</style>

<h1>Book Id</h1>
<h2>@Model.BookId</h2>
<h1>Book Title</h1>
<h2>@Model.Book.Name</h2>
<h1>Borrower Id</h1>
<h2>@Model.BorrowerId</h2>
<h1>Borrower Name</h1>
<h2>@Model.Reader.Name</h2>
<h1>Is Returned?</h1>
<h2>@Model.IsReturned</h2>

<a asp-asp-controller="Borrowing" asp-action="Index">Go Back</a>

asp.net-assignment-4/Views/Borrowing/Edit.cshtml
@model Borrowing
@{
    ViewData["title"] = "Edit a Borrowing";
}

<h1>Edit Borrowing:</h1>
<form method="post" asp-controller="Borrowing" asp-action="Edit" asp-route-id="@Model.Id">
    <input type="hidden" asp-for="Id"/>

    <label asp-for="BookId"></label>
    <input type="number" asp-for="BookId" placeholder="Enter Book Id" />
    <div>
        <span asp-validation-for="BookId"></span>
    </div>
    <label asp-for="BorrowerId"></label>
    <input type="number" asp-for="BorrowerId" placeholder="Enter Borrower Id" />
    <div>
        <span asp-validation-for="BorrowerId"></span>
    </div>
    <label asp-for="IsReturned"></label>
    <input type="checkbox" asp-for="IsReturned" />
    <div>
        <span asp-validation-for="IsReturned"></span>
    </div>
    <button type="submit">Save</button>
</form>

asp.net-assignment-4/Views/Borrowing/Index.cshtml
@model List<Borrowing>
@{
    ViewData["title"] = "All Borrowings";
}

<style>
    table 
    {
        border-collapse: collapse;
        width: auto;
    }

    /* Only apply border to the first four columns */
    th:nth-child(1),
    th:nth-child(2),
    th:nth-child(3),
    th:nth-child(4),
    td:nth-child(1),
    td:nth-child(2),
    td:nth-child(3),
    td:nth-child(4)
    {
        border: 1px solid black;
    }

    th, td 
    {
        padding: 4px;
        text-align: left;
    }

    td a 
    {
        margin-right: 8px;
    }

    input[type="text"] {
        width: 225px;
        margin-right: 1rem;
        margin-bottom: 1rem;
    }
</style>

<h1>All Borrowings:</h1>
<form asp-action="Index" method="get">
    <input type="text" name="search" placeholder="Search (Book Title, Borrower Name)" />
    <input type="submit" value="Search" />
</form>
@if(Model != null && Model.Count() > 0)
{

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Book</th>
                <th>Borrower</th>
                <th>Is Returned?</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var borrowing in Model)
            {
                <tr>
                    <td>@borrowing.Id</td>
                    <td>@borrowing.Book.Name</td>
                    <td>@borrowing.Reader.Name</td>
                    <td>@borrowing.IsReturned</td>
                    <td><a asp-controller="Borrowing" asp-action="Details" asp-route-id="@borrowing.Id">Details</a></td>
                    <td><a asp-controller="Borrowing" asp-action="Edit" asp-route-id="@borrowing.Id">Edit</a></td>
                    <td><a asp-controller="Borrowing" asp-action="Delete" asp-route-id="@borrowing.Id">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
}
<a asp-controller="Borrowing" asp-action="Add">Add</a>