asp.net-assignment-4/Models/Reader.cs
using System.ComponentModel.DataAnnotations;

namespace asp.net_assignment_4.Models
{
    public class Reader
    {
        [Key]
        [Required(ErrorMessage = "{0} is required")]
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        [EmailAddress(ErrorMessage = "{0} must be a valid email address.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        [Phone(ErrorMessage = "Invalid phone number format.")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Address { get; set; }
        public ICollection<Borrowing> Borrowings { get; set; } = new List<Borrowing>();
    }
}

asp.net-assignment-4/Controllers/ReaderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using asp.net_assignment_4.Models;
using asp.net_assignment_4.Data;

namespace asp.net_assignment_4.Controllers
{
    public class ReaderController : Controller
    {
        private readonly AppDbContext appDbContext;

        public ReaderController(AppDbContext appDbContext)
        {
            this.appDbContext = appDbContext;
        }

        // Get all readers
        [HttpGet]
        [Route("readers")]
        public async Task<IActionResult> Index(string search)
        {
            var readers = from r in appDbContext.Reader
                          select r;

            if (!string.IsNullOrEmpty(search))
            {
                readers = readers.Where(r => r.Name.Contains(search) ||
                                             r.Email.Contains(search));
            }

            return View(await readers.ToListAsync());
        }

        // Get certain reader
        [HttpGet]
        [Route("readers/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await appDbContext.Reader
                .Include(r => r.Borrowings)
                .ThenInclude(br => br.Book)
                .FirstOrDefaultAsync(r => r.Id == id));
        }

        // Get reader add page
        [HttpGet]
        [Route("readers/add")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Route("readers/add")]
        public async Task<IActionResult> Add(Reader reader)
        {
            if (ModelState.IsValid)
            {
                var newReader = new Reader()
                {
                    Name = reader.Name,
                    Email = reader.Email,
                    PhoneNumber = reader.PhoneNumber,
                    Address = reader.Address
                };
                await appDbContext.AddAsync(newReader);
                await appDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(reader);
        }

        // Get reader edit page
        [HttpGet]
        [Route("readers/edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await appDbContext.Reader.FirstOrDefaultAsync(r => r.Id == id));
        }

        // edit reader
        [HttpPost]
        [Route("readers/edit/{id}")]
        public async Task<IActionResult> Edit(Reader newReader)
        {
            if (ModelState.IsValid)
            {
                var reader = await appDbContext.Reader.FindAsync(newReader.Id);
                if (reader != null)
                {
                    reader.Name = newReader.Name;
                    reader.Email = newReader.Email;
                    reader.PhoneNumber = newReader.PhoneNumber;
                    reader.Address = newReader.Address;
                    await appDbContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(newReader);
        }

        // Delete reader
        [HttpGet]
        [Route("readers/delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var reader = await appDbContext.Reader.FindAsync(id);
            if (reader != null)
            {
                appDbContext.Reader.Remove(reader);
                await appDbContext.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

asp.net-assignment-4/Views/Reader/Add.cshtml
@model Reader
@{
    ViewData["title"] = "Add a Reader";
}

<h1>New Reader:</h1>
<form method="post" asp-controller="Reader" asp-action="Add">
    <label asp-for="Name"></label>
    <input type="text" asp-for="Name" placeholder="Enter Name" />
    <div>
        <span asp-validation-for="Name"></span>
    </div>
    <label asp-for="Email"></label>
    <input type="email" asp-for="Email" placeholder="Enter Email" />
    <div>
        <span asp-validation-for="Email"></span>
    </div>
    <label asp-for="PhoneNumber"></label>
    <input type="tel" asp-for="PhoneNumber" placeholder="Enter PhoneNumber" />
    <div>
        <span asp-validation-for="PhoneNumber"></span>
    </div>
    <label asp-for="Address"></label>
    <input type="text" asp-for="Address" placeholder="Enter Address" />
    <div>
        <span asp-validation-for="Address"></span>
    </div>
    <button type="submit">Add</button>
</form>

asp.net-assignment-4/Views/Reader/Details.cshtml
@model Reader
@{
    ViewData["title"] = "Reader";
}
<style>
    h2{
        font-weight:normal;
    }

    table {
        border-collapse: collapse;
        width: auto;
    }

    th, td {
        border: 1px solid black;
        padding: 4px;
        text-align: left;
    }

        td a {
            margin-right: 8px;
        }
</style>

<h1>Title</h1>
<h2>@Model.Name</h2>
<h1>Email</h1>
<h2>@Model.Email</h2>
<h1>Phone Number</h1>
<h2>@Model.PhoneNumber</h2>
<h1>Address</h1>
<h2>@Model.Address</h2>

<h1>Borrowings</h1>
<table>
    <thead>
        <tr>
            <th>Borrowing Id</th>
            <th>Book Name & Id</th>
            <th>Is Returned?</th>
        </tr>
    </thead>
    <tbody>

            @foreach (var borrowing in Model.Borrowings)
            {
            <tr>
                <td>@borrowing.Id</td>
                <td>@borrowing.Book.Name (ID: @borrowing.BookId)</td>
                <td>@(borrowing.IsReturned ? "Yes" : "No")</td>
            </tr>
            }

    </tbody>
</table>

<a asp-asp-controller="Reader" asp-action="Index">Go Back</a>

asp.net-assignment-4/Views/Reader/Edit.cshtml
@model Reader
@{
    ViewData["title"] = "Edit a Reader";
}

<h1>Edit Reader:</h1>
<form method="post" asp-controller="Reader" asp-action="Edit">
    <label asp-for="Name"></label>
    <input type="text" asp-for="Name" placeholder="Enter Title" />
    <div>
        <span asp-validation-for="Name"></span>
    </div>
    <label asp-for="Email"></label>
    <input type="email" asp-for="Email" placeholder="Enter Email" />
    <div>
        <span asp-validation-for="Email"></span>
    </div>
    <label asp-for="PhoneNumber"></label>
    <input type="tel" asp-for="PhoneNumber" placeholder="Enter Phone Number" />
    <div>
        <span asp-validation-for="PhoneNumber"></span>
    </div>
    <label asp-for="Address"></label>
    <input type="text" asp-for="Address" placeholder="Enter Address" />
    <div>
        <span asp-validation-for="Address"></span>
    </div>
    <button type="submit">Save</button>
</form>

asp.net-assignment-4/Views/Reader/Index.cshtml
@model List<Reader>
@{
    ViewData["title"] = "All Readers";
}

<style>
    table 
    {
        border-collapse: collapse;
        width: auto;
    }

    /* Only apply border to the first three columns */
    th:nth-child(1),
    th:nth-child(2),
    th:nth-child(3),
    td:nth-child(1),
    td:nth-child(2),
    td:nth-child(3)
    {
        border: 1px solid black;
    }

    th, td 
    {
        padding: 4px; 
        text-align: left;
    }

    td a 
    {
        margin-right: 8px;
    }

    input[type="text"] {
        margin-right: 1rem;
        margin-bottom: 1rem;
    }
</style>

<h1>All Readers:</h1>
<form asp-action="Index" method="get">
    <input type="text" name="search" placeholder="Search (Name, Email)" />
    <input type="submit" value="Search" />
</form>
@if(Model != null && Model.Count() > 0)
{

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var reader in Model)
            {
                <tr>
                    <td>@reader.Id</td>
                    <td>@reader.Name</td>
                    <td>@reader.Email</td>
                    <td><a asp-controller="Reader" asp-action="Details" asp-route-id="@reader.Id">Details</a></td>
                    <td><a asp-controller="Reader" asp-action="Edit" asp-route-id="@reader.Id">Edit</a></td>
                    <td><a asp-controller="Reader" asp-action="Delete" asp-route-id="@reader.Id">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
}
<a asp-controller="Reader" asp-action="Add">Add</a>